FILE_STRUCTURE = {
    "stock_expo.csv": {
        "file_format": r"ael_\d{8}.csv",
        "date_str": True,
        "latest_file": False,
        "date_format": "%d%m%Y",
        "compressed": False,
        "path": "/FaoCommon/Limit Files/ael_{0}.csv",
        "name": "Stock Exposure",
        "time": ["08:45"],
    },
    "cn.csv": {
        "file_format": r"F_CN01_NSE_\d{8}.CSV",
        "date_str": True,
        "latest_file": False,
        "latest_file": True,
        "date_format": "%d%m%Y",
        "compressed": True,
        "path": "/FaoCommon/MarketReports/F_CN01_NSE_{0}.CSV.gz",
        "name": "CN",
        "time": ["08:45"],
    },
    "index_expo.csv": {
        "file_format": r"ael_NIFTY_Options.csv",
        "date_str": False,
        "latest_file": False,
        "compressed": False,
        "path": "/FaoCommon/Limit Files/ael_NIFTY_Options.csv",
        "name": "Exposure",
        "time": ["08:45"],
    },
    "option_expo.csv": {
        "file_format": r"F_AEL_OTM_CONTRACTS_\d{8}.csv",
        "date_str": True,
        "latest_file": False,
        "date_format": "%d%m%Y",
        "compressed": True,
        "path": "/FaoCommon/Limit Files/F_AEL_OTM_CONTRACTS_{0}.csv.gz",
        "name": "Option Exposure",
        "time": ["08:45"],
    },
    "risk.spn": {
        "file_format": r"nsccl.\d{8}.i01.spn",
        "date_str": True,
        "latest_file": False,
        "date_format": "%Y%m%d",
        "compressed": True,
        "path": "/FaoCommon/Parameter/nsccl.{0}.i01.spn.gz",
        "name": "Span",
        "time": ["08:45"],
    },
    "contract.txt": {
        "file_format": r"contract.txt",
        "date_str": False,
        "latest_file": False,
        "compressed": True,
        "path": "/FaoCommon/contract.gz",
        "name": "Instrument",
        "time": ["08:45"],
    },
}
